### ISSUE TITLE
Installation of byzantium configd.py

### ISSUE THREAD

**Issue by MasterSumen3110** [Byzantium/ByzPi#35]
Hi, I have tried to follow the steps. However, got this error. Could anyone help me on this? 

Attempting to configure interface wlan1.
Setting wireless interface wlan1 to down.
Attempting to configure the wireless interface.  Try: 0
ESSID is correct.
Mode is correct.
Failed to set up the interface properly.  Retrying...
Attempting to configure the wireless interface.  Try: 1
ESSID is correct.
Mode is correct.
Failed to set up the interface properly.  Retrying...
Attempting to configure the wireless interface.  Try: 2
ESSID is correct.
Mode is correct.
Failed to set up the interface properly.  Retrying...
Setting wireless interface wlan1 to up.
Attempting to configure the wireless interface.  Try: 0
ESSID is correct.
Mode is correct.
BSSID is correct.
Channel is correct.
Turning interface wlan1 up to continue configuration.
Probing for IP address for the mesh interface.
Traceback (most recent call last):
  File "byzantium_configd.py", line 187, in <module>
    ip_in_use = subprocess.call(arping)
  File "/usr/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by virtadpt** [comment]
You don't have `arping` installed.
